= OrderTransformer

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

toc::[]

Welcome to your new gem!In this directory, you'll find the files you need to be able to package up your Ruby library into a gem.Put your Ruby code in the file `lib/data_transformer`.To experiment with that code, run `bin/console` for an interactive prompt.

TODO: Delete this and the text above, and describe your gem

== Installation


Add this line to your application's Gemfile:

[source,ruby]
----
gem 'order_transformer'
----

And then execute:

    $ bundle install

Or install it yourself as:

    $ gem install data_transformer

== Usage

Given the following definitions
[%collapsible]
====
[source,ruby,linenums]
-------
include::spec/dsl_spec.rb[tag=definition]
-------
====

Given the following input
[%collapsible]
====
[source,ruby,linenums]
-------
include::spec/dsl_spec.rb[tag=input]
-------
====

Given the following call
[%collapsible]
====
[source,ruby,linenums]
-------
include::spec/dsl_spec.rb[tag=call]
-------
====

The following output is expected
[%collapsible]
====
[source,ruby,linenums]
-------
include::spec/dsl_spec.rb[tag=output]
-------
====

== Development

After checking out the repo, run `bin/setup` to install dependencies.Then, run `rake spec` to run the tests.You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`.To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/data_transformer.

